### ISSUE TITLE
Help with documentation

### ISSUE THREAD

**Issue by Gaurav-Original-ClassicShellTester** [hst125fan/mtpmount#3]
I find the documentation unclear and confusing. How exactly do I mount?

I did mtpmount list available which returned this:

`Available Connections and Storage Media:`
`Connection X: USB 3 SATA TLC Samsung T5 SSD: Contains 1 storages that can be mounted`
` |-- Storage X: [ID #0]`
`Connection : Contains 2 storages that can be mounted`
` |-- Storage Internal shared storage [ID #1]`
 `|-- Storage SanDisk SD card [ID #2]`
`Use mount command to make one of them a windows removable drive`

But what is the devicename in this and the storage name? Does it need double quotes? I tried mounting by ID too. That also failed. Can you document it better please?

I get errors like "Cannot establish connection to device. Is <devicename> really connected (and spelled correctly)?". Why is drive letter in the explained syntax in brackets?

`mount <devicename> <storagename> (<driveletter>)`  ?

UPDATE: I figured it out. The ID needs to be in double quotes:

`mtpmount mount "#1" Y:`

OR

`mtpmount.exe mount "my phone's name" "Internal shared storage" Y:`

**Comment by gabri-ns** [comment]
hai @Gaurav-Original-ClassicShellTester
i still can not work it out
adding double quotes doesn't work

here is my output of list available
```Available Connections and Storage Media:
Connection SD64GB: Contains 1 storages that can be mounted
 |-- Storage E: [ID #0]
Connection : Contains 2 storages that can be mounted
 |-- Storage MICROSD64GB [ID #1]
 |-- Storage Internal shared storage [ID #2]
```

doing `mtpmount SD64GB E:` work with output
`Drive Y:\ is now SD64GB\E:. Don't forget to unmount the drive (using unmount command) before disconnecting your device`
but `mtpmount mount "#1"` or `mtpmount mount "#1" X:` doesn't work

how do you make it work?

UPDATE:
i can make it work
doing `mtpmount mount #1` without double quote work
i just remove the device and then connect it again
my device list get updated with new id
```
Available Connections and Storage Media:
Connection SD64GB: Contains 1 storages that can be mounted
 |-- Storage E: [ID #0]
Connection POCO: Contains 2 storages that can be mounted
 |-- Storage MICROSD64GB [ID #3]
 |-- Storage Internal shared storage [ID #4]
```

if it still does not work, rename your device and try reconnect again
if you notice, my device got new name on new device list above
i didn't tell about it just wondering wether just reconnecting the device work

please share here your experience
